env:
  global:
    - CC_TEST_REPORTER_ID=0821c701bb20ce2afc198c727f4a8aefaecc87bf6af23f1aafd2e0fe1b09d8bf
language: node_js
node_js:
  - 9
cache: yarn
before_install:
  - yarn global add lerna
  - yarn global add jest
  - yarn global add codecov
install:
  - yarn
  - yarn compile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn clean
  - yarn test
  - codecov
after_script:
  - ./cc-test-reporter upload-coverage < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
